spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: trainschedule
# Specify the path of the OpenAPI documentation
springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html
  swagger-ui.enabled: true

